'use client';

import Link from 'next/link';
import { Minus, Plus, Trash2, ShoppingBag } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Container } from '@/components/ui/Container';
import { Button } from '@/components/ui/Button';
import { useCartStore } from '@/stores/cart';
import type { Product } from '@/types/shop';
import { formatVnd } from '@/lib/utils';

export default function CartPage(){const items=useCartStore(s=>s.items),setQuantity=useCartStore(s=>s.setQuantity),remove=useCartStore(s=>s.remove);const [products,setProducts]=useState<Record<string,Product>>({});useEffect(()=>{if(!items.length)return;Promise.all(items.map(i=>fetch(`/api/products/by-id/${i.productId}`).then(r=>r.json()))).then(rows=>{const map:Record<string,Product>={};rows.forEach(j=>{if(j.ok)map[j.data.id]=j.data});setProducts(map)}).catch(()=>undefined)},[items]);const subtotal=items.reduce((n,i)=>n+(products[i.productId]?.price??0)*i.quantity,0);return <Container className="py-12"><div className="mb-8"><div className="text-xs font-black uppercase tracking-[.24em] text-cyan-300/70">Cart</div><h1 className="mt-2 text-4xl font-black">Giỏ hàng</h1></div>{!items.length?<div className="lv-glass rounded-3xl p-16 text-center"><ShoppingBag className="mx-auto h-9 w-9 text-white/30"/><div className="mt-5 font-black">Giỏ hàng đang trống</div><Link href="/shop" className="mt-5 inline-block text-sm text-cyan-300">Khám phá shop →</Link></div>:<div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{items.map(item=>{const p=products[item.productId];return <div key={item.productId} className="lv-glass rounded-2xl p-4"><div className="flex items-center gap-4"><div className="h-16 w-24 rounded-xl bg-gradient-to-br from-purple-500/20 to-cyan-400/10"/><div className="min-w-0 flex-1"><Link href={p?`/product/${p.slug}`:'#'} className="font-bold hover:text-cyan-200">{p?.name??'Đang tải...'}</Link><div className="mt-1 text-xs text-white/40">{p?formatVnd(p.price):''}</div></div><div className="flex items-center gap-2"><button onClick={()=>setQuantity(item.productId,item.quantity-1)} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10"><Minus className="h-3 w-3"/></button><span className="w-6 text-center text-sm font-bold">{item.quantity}</span><button onClick={()=>setQuantity(item.productId,item.quantity+1)} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10"><Plus className="h-3 w-3"/></button></div><button onClick={()=>remove(item.productId)} className="grid h-9 w-9 place-items-center rounded-lg border border-rose-400/15 bg-rose-400/5 text-rose-200"><Trash2 className="h-4 w-4"/></button></div></div>})}</div><div className="lv-glass h-fit rounded-2xl p-6"><div className="text-xs uppercase tracking-[.2em] text-white/35">Tạm tính</div><div className="mt-2 text-3xl font-black">{formatVnd(subtotal)}</div><p className="mt-3 text-xs leading-5 text-white/35">Checkout sẽ tính lại giá, tồn kho và voucher ở server.</p><Link href="/checkout"><Button className="mt-6 w-full">Tiến hành thanh toán</Button></Link></div></div>}</Container>}
