import { getAdminDb } from '@/lib/firebase/admin';
import { requireAdmin } from '@/lib/security/auth';
import { productSchema } from '@/lib/validation/schemas';
import { slugify } from '@/lib/utils';
import { adminError } from '@/lib/security/admin-response';
import { fail, ok } from '@/lib/api';

export async function GET(request:Request){try{await requireAdmin(request);const snap=await getAdminDb().collection('products').orderBy('createdAt','desc').limit(200).get();return ok({items:snap.docs.map(d=>({id:d.id,...d.data()}))});}catch(e){return adminError(e)}}
export async function POST(request:Request){try{const auth=await requireAdmin(request);const parsed=productSchema.safeParse(await request.json());if(!parsed.success)return fail(parsed.error.issues[0]?.message??'Dữ liệu sản phẩm không hợp lệ.');let slug=slugify(parsed.data.name)||`product-${Date.now()}`;const db=getAdminDb();const same=await db.collection('products').where('slug','==',slug).limit(1).get();if(!same.empty)slug=`${slug}-${Date.now().toString(36)}`;const ref=db.collection('products').doc();const now=Date.now();await ref.set({id:ref.id,name:parsed.data.name,slug,description:parsed.data.description,category:parsed.data.category,price:parsed.data.price,originalPrice:parsed.data.originalPrice??null,discount:parsed.data.originalPrice&&parsed.data.originalPrice>parsed.data.price?Math.round(100-(parsed.data.price/parsed.data.originalPrice)*100):0,thumbnail:parsed.data.thumbnail,images:parsed.data.images??[],inventoryCount:parsed.data.inventoryCount??0,soldCount:0,viewCount:0,status:parsed.data.status??'active',featured:parsed.data.featured??false,badge:parsed.data.badge??'',features:parsed.data.features??[],fileAsset:parsed.data.fileAsset??null,createdAt:now,updatedAt:now,createdBy:auth.uid});return ok({id:ref.id},201);}catch(e){return adminError(e)}}
export async function PATCH(request:Request){try{await requireAdmin(request);const body=await request.json();const id=String(body.id||'');if(!id)return fail('Thiếu product id.');const parsed=productSchema.partial().safeParse(body.data??body);if(!parsed.success)return fail(parsed.error.issues[0]?.message??'Dữ liệu không hợp lệ.');const update: Record<string, unknown>={...parsed.data,updatedAt:Date.now()};if(typeof update.name==='string')update.slug=slugify(update.name);await getAdminDb().collection('products').doc(id).update(update);return ok({updated:true});}catch(e){return adminError(e)}}
export async function DELETE(request:Request){try{await requireAdmin(request);const {searchParams}=new URL(request.url);const id=searchParams.get('id');if(!id)return fail('Thiếu product id.');await getAdminDb().collection('products').doc(id).update({status:'archived',updatedAt:Date.now()});return ok({deleted:true});}catch(e){return adminError(e)}}
