'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Container } from '@/components/ui/Container';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { useAuth } from '@/components/auth/AuthProvider';
import { toast } from 'sonner';
export default function SettingsPage(){const {user,loading}=useAuth();const [displayName,setDisplayName]=useState(''),[photoURL,setPhotoURL]=useState(''),[saving,setSaving]=useState(false);useEffect(()=>{let cancelled=false;const load=async()=>{if(!user)return;try{const token=await user.getIdToken();const r=await fetch('/api/profile',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)return;const j=await r.json();if(!cancelled&&j?.ok){setDisplayName(j.data?.displayName??'');setPhotoURL(j.data?.photoURL??'')}}catch{}};void load();return()=>{cancelled=true}},[user]);async function save(){if(!user)return;setSaving(true);try{const t=await user.getIdToken();const r=await fetch('/api/profile',{method:'PATCH',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({displayName,photoURL})});const j=await r.json();j.ok?toast.success('Đã lưu cài đặt.'):toast.error(j.error?.message??'Không thể lưu.')}finally{setSaving(false)}}if(loading)return <Container className="py-12">Loading...</Container>;if(!user)return <Container className="py-12"><Link href="/login" className="text-cyan-300">Đăng nhập để mở Settings.</Link></Container>;return <Container className="max-w-2xl py-12"><div className="lv-glass rounded-3xl p-7"><div className="text-xs font-black uppercase tracking-[.2em] text-orange-300/70">Settings</div><h1 className="mt-2 text-4xl font-black">Cài đặt tài khoản</h1><div className="mt-7 space-y-4"><label className="block text-xs font-bold text-white/55">Tên hiển thị<Input className="mt-2" value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label className="block text-xs font-bold text-white/55">Avatar URL HTTPS<Input className="mt-2" value={photoURL} onChange={e=>setPhotoURL(e.target.value)}/></label><Button loading={saving} onClick={save}>Lưu thay đổi</Button></div></div></Container>}
