'use client';

import Link from 'next/link';
import { Box, FileUp, Gamepad2, LayoutDashboard, ListOrdered, Receipt, Settings, ShieldCheck, TicketPercent, Users, Wallet } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { usePathname, useRouter } from 'next/navigation';

const links=[['/admin','Dashboard',LayoutDashboard],['/admin/users','Users',Users],['/admin/products','Products',Box],['/admin/inventory','ACC Inventory',Gamepad2],['/admin/files','Files',FileUp],['/admin/orders','Orders',ListOrdered],['/admin/deposits','Deposits',Wallet],['/admin/nappay','NAPPay',Receipt],['/admin/sepay','SePay',Wallet],['/admin/vouchers','Vouchers',TicketPercent],['/admin/notifications','Notifications',Receipt],['/admin/settings','Settings',Settings]] as const;
export function AdminShell({children}:{children:ReactNode}){const {user,loading}=useAuth();const pathname=usePathname();const router=useRouter();const [allowed,setAllowed]=useState<boolean|null>(null);useEffect(()=>{let cancelled=false;const check=async()=>{if(loading)return;if(!user){setAllowed(false);router.replace('/login');return;}try{const token=await user.getIdToken(true);const response=await fetch('/api/auth/me',{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Unauthorized');const data=await response.json();const isAdmin=data?.ok&&data?.data?.role==='admin';if(cancelled)return;setAllowed(Boolean(isAdmin));if(!isAdmin)router.replace('/');}catch{if(!cancelled){setAllowed(false);router.replace('/');}}};void check();return()=>{cancelled=true}},[user,loading,router]);if(allowed!==true)return <div className="mx-auto max-w-7xl px-4 py-24 text-center text-white/30">Checking authorization...</div>;return <div className="mx-auto grid max-w-7xl gap-5 px-4 py-6 lg:grid-cols-[240px_1fr]"><aside className="lv-glass h-fit rounded-2xl p-3 lg:sticky lg:top-24"><div className="mb-3 flex items-center gap-2 px-3 py-3 text-xs font-black uppercase tracking-[.2em] text-white/50"><ShieldCheck className="h-4 w-4 text-cyan-300"/>Admin</div>{links.map(([href,label,Icon])=><Link key={href} href={href} className={`mb-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${pathname===href?'bg-white/[.08] text-white':'text-white/45 hover:bg-white/[.05] hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</Link>)}</aside><section className="min-w-0">{children}</section></div>}
